{{- if .Values.smtp.enabled -}}
{{- if and (.Values.smtp.outgoingSMTP.enabled) (not .Values.smtp.outgoingSMTP.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
  name: {{ template "mailhog.outgoingSMTPSecret" . }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{ .Values.smtp.outgoingSMTP.fileName }}: {{ .Values.smtp.outgoingSMTP.fileContents | toJson | b64enc }}
{{- end -}}
{{- end -}}