{{- if .Values.smtp.enabled -}}
{{- if and (.Values.smtp.auth.enabled) (not .Values.smtp.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
  name: {{ template "mailhog.authFileSecret" . }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{ .Values.smtp.auth.fileName }}: {{ .Values.smtp.auth.fileContents }}
{{- end -}}
{{- end -}}