{{- if .Values.smtp.enabled -}}
{{- if .Values.smtp.ingress.enabled -}}
{{- $fullName := include "mailhog.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mailhog.labels" . | nindent 4 }}
  {{- with .Values.smtp.ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.smtp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.smtp.ingress.ingressClassName }}
  ingressClassName: {{ .Values.smtp.ingress.ingressClassName }}
{{- end }}
  rules:
#    - host:  {{ .Values.smtp.ingress.host }}
    - host:  {{ default (printf "%s%s" .Release.Namespace "-mails.dev.numerique-interieur.com")  .Values.smtp.ingress.hostOverride }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
{{- end }}
{{- end -}}