{{- if .Values.passage2.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: saml-keycloak
  name: saml-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saml-keycloak
  template:
    metadata:
      labels:
        app: saml-keycloak
    spec:
      containers:
        - image: quay.io/keycloak/keycloak:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          args:
            - start-dev
            - --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: passage2-keycloak-auth
                  key: keycloak-admin-login
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passage2-keycloak-auth
                  key: keycloak-password
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_PROXY
              value: "edge"
          readinessProbe:
            httpGet:
              path: "/auth/realms/master"
              port: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          name: keycloak
          volumeMounts:
            - mountPath: /opt/keycloak/data/import/
              name: realm-keycloak
      volumes:
        - configMap:
            name: realm-keycloak
          name: realm-keycloak
{{- end -}}