{{- if .Values.passage2.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rpa
  name: rpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpa
  template:
    metadata:
      labels:
        app: rpa
    spec:
      initContainers:
        - name: init-saml
          image: praqma/network-multitool
          command: ["sh", "/scripts/fetch-saml.sh"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: passage2-keycloak-auth
                  key: keycloak-admin-login
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passage2-keycloak-auth
                  key: keycloak-password
          volumeMounts:
            - mountPath: /scripts
              name: saml-keycloak
            - mountPath: /saml
              name: saml
      containers:
        - image: {{ .Values.passage2.reverseproxy.image }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          name: httpd
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /scripts
              name: saml-keycloak
            - mountPath: /saml
              name: saml
            - mountPath: /opt/bitnami/apache/conf/httpd.conf
              name: apache2-conf
              subPath: httpd.conf
            - mountPath: /opt/bitnami/apache/conf/vhosts
              name: vhost-passage
      volumes:
        - emptyDir: {}
          name: saml
        - configMap:
            name: apache2-conf
          name: apache2-conf
        - configMap:
            name: vhost-passage
          name: vhost-passage
        - configMap:
            name: saml-keycloak
          name: saml-keycloak
{{- end -}}
