{{- if .Values.passage2.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rpa
spec:
  rules:
    # rpa-127-0-0-1.xip.lhjmmc.cn
    - host:  {{ .Values.passage2.reverseproxy.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.passage2.reverseproxy.service.name }}
                port:
                  number: {{ .Values.passage2.reverseproxy.service.port }}
{{- end -}}