{{- if .Values.passage2.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saml-kc
spec:
  rules:
    # kc-127-0-0-1.xip.lhjmmc.cn
    - host: {{ .Values.passage2.mockpassage2.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.passage2.mockpassage2.service.name }}
                port:
                  number: {{ .Values.passage2.mockpassage2.service.port }}
{{- end -}}