{{- if .Values.passage2.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: passage2-keycloak-auth
data:
  keycloak-password: {{ .Values.passage2.mockpassage2.adminPassword | b64enc }}
  keycloak-admin-login: {{ .Values.passage2.mockpassage2.adminLogin | b64enc }}
{{- end -}}