{{- if .Values.passage2.enabled -}}
{{- if .Values.passage2.demoApp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: whoami-svc
spec:
  type: ClusterIP
  selector:
    app: whoami
  ports:
    - port: 8080
{{- end -}}
{{- end -}}